seed: 42
num_epoch: 2000
num_step: 20
agent_continuous:
  _target_: A2C.agent.A2Cagent
  hidden_dim: 256 
  gamma: 0.99
  actor_lr: 3e-4
  critic_lr: 1e-3
  actor_weight: 1.0
  critic_weight: 0.5
  entropy_weight: 0.01