seed: 42
num_epoch: 2000
num_step: 20
env_id: "Pendulum-v1"
agent_continuous:
  _target_: SAC.agent.SACagent
  hidden_dim: 256
  alpha: 0.2      # continuous environment
  gamma: 0.99
  tau: 0.005
  act_lr: 3e-4
  state_lr: 3e-4
  state_act_lr: 3e-4
  capacity: 100000
  batch_size: 16