seed: 42
num_epoch: 1000        # total episodes
num_step: 20          # steps per episode
env_id: "Pendulum-v1"
OUActionNoise:
  sigma: 0.15
  theta: 0.2
  dt: 0.01
agent_continuous:
  _target_: DDPG.agent.DDPGagent
  hidden_dim: 256
  tau: 0.001
  gamma: 0.99
  actor_lr: 0.000025
  critic_lr: 0.00025
  capacity: 1000000
  batch_size: 64